ToDo/ToDo/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("form/", include("form.urls"))
]

ToDo/form/urls.py
from django.urls import path
from . import views

app_name= "form"

urlpatterns = [
    path("", views.login_user, name="loginUser"),
    path("register/", views.register_user, name="registerUser"),
    path("main/", views.mainf , name="main")
]

ToDo/form/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
# Create your models here.


class Users(AbstractUser) :
    email = models.EmailField(max_length=256,unique=True,blank=False, null=False)
    username=models.CharField(max_length=64, blank=False, unique=False,null=False)
    USERNAME_FIELD= 'email'
    REQUIRED_FIELDS = ['username']
    
    def __str__(self):
        return self.username

ToDo/form/views.py
from ast import Not
from asyncio.windows_events import NULL
from sqlite3 import IntegrityError
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth import login, logout, authenticate
from .models import Users

def login_user(request) :
    if request.method == "POST" :
        email = request.POST['email']
        passs= request.POST['password']
        auth = authenticate(username=email, password=passs)
        if auth is not None : 
            login(request,request.user)
            return HttpResponseRedirect(reverse("form:main"))
        else : 
            return render(request, "form/login.html",{
                "errorr": True,
                "error" : "wrong info"
            })
    else: 
        return render(request, "form/login.html")

def register_user(request):
    if request.method == "POST" :
        email = request.POST['email']
        username= request.POST['name']
        passw = request.POST['pass']
        confpass= request.POST['confpass']
        
        if (not email and not username and not passw) or (not email and not username) or not email or not username or not passw: 
            return render(request, 'form/register.html',{
                'emailerror' : 'email required !' if not email else '',
                'uerror' : 'username required !' if not username else '',
                'perror' : 'password required !' if not passw else ' '

            })
        # if not email and not username: 
        #     return render(request, "form/register.html", {
        #     'emailerror' : "email required !",
        #     "uerror" : "username required !"
        # })
        # if not username: 
        #     return render(request, "form/register.html", {
        #         'uerror' : "username required !"
        #     })
        # if not email: 
        #     return render(request, "form/register.html", {
        #         'emailerror' : "email required !"
        #     })
        
        
        if passw != confpass : 
            return render(request, "form/register.html", {
                'error' : "passwords don't match !"
            })

        auth = authenticate(username=email, passwrod=passw)
        if auth is not None :
            return render(request, "form/register.html", {
                'error': "email already used"
            })
        else :
            try : 
                user = Users.objects.create_user(email = email, username = username, password=passw)
            except :
                return render(request, "form/register.html",{
                    'error' : "email already exists "
                }) 
            login(request, user)
            return HttpResponseRedirect(reverse("form:main"))
    else : 
        return render(request, "form/register.html")


def mainf(request):
    return render(request, "form/main.html")

ToDo/form/templates/form/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
    {% block link %} {% endblock %}
    <title>{% block title%} {% endblock %}</title>
</head>
<body>
    {% block body %}{% endblock %}
</body>
</html>

ToDo/form/templates/form/login.html
{% extends "form/layout.html" %}
{% load static %}

{% block link %} 
 <link rel="stylesheet" href="{% static 'styles.css'%}">
{% endblock %}

{% block title%}
    login
{% endblock %}


{% block body %}
    <div class="login-container"> 
        <div class="wrapper">
            <div class="signin">
                <h1>Sign In</h1>
                
                    <p style="display:inline;color:red;">{{error}}</p>
                
                <form action="{% url 'form:loginUser'%}" method="post">
                    {% csrf_token %}
                    <div class="input" id="username" >
                        <label>email</label>
                        <input type="email" name="email" autocomplete="off" autofocus>
                    </div>
                    <div class="input" id="pass">
                        <label>password</label>
                        <input type="password" name="password" autocomplete="off">
                    </div class="input">


                    <div id='remember'>
                        <input type="checkbox" value="Isremember" id="rememberme"> 
                        <label for="rememberme">Remember Me</label>
                    </div>
                    
                    <input type="submit" id="submit">
                    <p>Don't have an account ? <a href="{% url 'form:registerUser'%}">Sign up</a></p>
                </form>
            </div>
            <div class="socialmedia">
                <h3>login with social media</h3>
                <div class="buttons">   
                    <!-- Facebook -->  
                    <a class="btn btn-primary" style="border-radius:30px;padding:0;line-height:0;background-color: #3b5998;" href="#!" role="button">
                        <ion-icon name="logo-facebook" style="padding:5px;margin:0;font-size: 30px;"></ion-icon>
                    </a>
                    <!-- Twitter -->
                    <a class="btn btn-primary btn-lg" style="border-radius:30px;padding:0;line-height:0;background-color: #55acee;" href="#!" role="button">
                        <ion-icon name="logo-twitter" style="padding:5px;margin:0;font-size: 30px;"></ion-icon>
                    </a>
                    <!-- Instagram -->
                    <a class="btn btn-primary" style="border-radius:30px;padding:0;line-height:0;background-color: #ac2bac;" href="#!" role="button"> 
                        <ion-icon name="logo-instagram" style="padding:5px;margin:0;font-size: 30px;"></ion-icon>
                    </a>
                </div>
                
            </div>
        </div>
        <div class="image">
            <img id="ash" src="{% static '/imgs/1.jpg' %}" alt="Ash">
        </div>
    </div>





<script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></script>
<script nomodule src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"></script>
{% endblock %}

ToDo/form/templates/form/main.html
{% extends 'form/layout.html'%}

{% block link %}
{% endblock %}

{% block titile%}
    main page
{% endblock%}
 
{% block body %}
    email : {{request.user.email}}
    pass :   {{request.user.password}}
    username : {{request.user.username}}
{% endblock%}

ToDo/form/templates/form/register.html
{%extends "form/layout.html"%}
{% load static %}


{% block link %} 
 <link rel="stylesheet" href="{% static 'styles2.css'%}">
{% endblock %}

{% block title%}
    register
{% endblock %}

{% block body %}
<main>
    <div class="content">
        <div class="image">
            <img src="{% static 'imgs/44.jpg'%}" alt="writing">
        </div>
        <div class="wrapper">
            <div class="registration">
                <h2>Register !  <span style="margin-left:3rem;color:red;font-size: 1rem;">{{error}}</span></h2>
                <form id="regform" action="" method="post">
                    {%csrf_token%}

                    <!-- username  -->
                    <div class="dif">
                        <label for="name_box">Name</label>
                        <input type="text" autocomplete="off" name="name" id="name_box" required> 
                        <span style="transform:translateY(-.6rem); color:red;">{{uerror}}</span>
                    </div>


                    <!-- email -->
                    <div class="dif">
                        <label for="email_box">Email</label>
                        <input type="Email" autocomplete="off" name="email" id="email_box" required>
                        <span style="transform:translateY(-.6rem); color:red;">{{emailerror}}</span>
                    </div>

                    <!-- password -->
                    <div class="dif">
                        <label for="pass_box">Password</label>
                        <input type="Password" autocomplete="off" name="pass" id="pass_box" required>
                        <span id="perr" style="transform:translateY(-.6rem); color:red; display:none;">password required !</span>
                    </div>

                    <!-- confirm password -->
                    <div class="dif">
                        <label for="conf_box">Confirm Password</label>
                        <input type="Password" autocomplete="off" name="confpass" id="conf_box">
                        <span style="transform:translateY(-.6rem); color:red;">{{perror}}</span>
                    </div>

                    <!-- agree checkbox -->
                    <div id="agree">
                        <input id="agree" type="checkbox">
                        <label for="agree"><p>Agree to our <a href="#">Terms and Conditions</a></p></label>
                    </div>

                    <!-- buttons  -->
                    <div class="btns">
                        <button type="submit" value="Register" id="registerbttnn" class="btn btn-primary btn-lg">Register</button>
                        <p>Or</p>
                        <a href="{% url 'form:loginUser'%}" class="btn btn-primary btn-xs">Sign in</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</main>




<script>
    let checkbox= document.getElementById("agree")
    let registerBtn = document.getElementById("registerbttnn")

    let pass = document.getElementById("pass_box")
    let perror = document.getElementById("perr")
    // let confpass = document.getElementsById("agconf_boxree")
    // let email = document.getElementsById("email_box")
    // let name = document.getElementsById("name_box")
   


    
    
    window.onload= ()=>{
        
        registerBtn.disabled = true;

        checkbox.addEventListener('change',function(e){
                if (e.target.checked == true){
                    registerBtn.disabled = false;
                }else{
                    registerBtn.disabled = true;
                }
            })
        }
   

        registerBtn.addEventListener('click', function(e){
            console.log(pass.value)
            if (pass.value.length == 0){
                e.preventDefault()
                perror.style.display = "inline"
            }
            else {
                perror.style.display = 'none'
            }
        })

</script>
{% endblock %}